title: Tech Database
description: Base de dados pessoal de informações sobre TI.
remote_theme: "mmistakes/minimal-mistakes@4.28.1"
minimal_mistakes_skin: "default"
search: true
plugins:
  - jekyll-include-cache
