title: Tech Database
description: Base de dados pessoal de informações sobre TI.
locale: "pt-BR"
remote_theme: "JediFonseca/minimal-mistakes"
minimal_mistakes_skin: "catppuccin_mocha"
search: true
plugins:
  - jekyll-include-cache
author:
  name: "Jedi Fonseca"
  avatar: "/assets/images/avatar.jpg"
  bio: "Estudante de Mecânica de Manutenção Aeronáutica, entusiasta de TI, F1 e aviação. Keep the blue side up!"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jedifonseca/"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JediFonseca"
